version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    parallelism: 4 
    resource_class: jkscci/k8-eks
    steps:
      - run: echo "Hi I'm on Runners!"
